version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - app
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "backend-container"
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
    networks:
      - app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client-container"
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app
networks:
  app: